server {
    listen 80;
    server_name localhost;

    # 1. Root & Index
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 301 /qc/;
    }

    location /qc {
        try_files $uri $uri/ /qc/index.html;
    }

    location /proxy/qc/ {
        # Strip the "/proxy/qc/" prefix before sending to backend
        rewrite ^/proxy/qc/(.*) /$1 break;

        proxy_pass http://10.10.12.12:8090;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /proxy/user/ {
        # Rewrite logic taken from your vite.config.js:
        # It replaces "/proxy/user" with "/api/user"
        rewrite ^/proxy/user/(.*) /api/user/$1 break;

        proxy_pass https://dev.fpsmonitoring.com;

        proxy_set_header Host $host;
        proxy_ssl_server_name on; # Required because target is HTTPS
    }
#
#     error_page 404 /qc/index.html;
#     error_page 500 502 503 504 /50x.html;
#     location = /50x.html {
#         root /usr/share/nginx/html;
#     }

    error_page 404 /qc/index.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    location ~* \.(?:ico|css|js|map|woff|woff2|ttf|otf|eot|ttc|ttf|jpg|jpeg|gif|png|svg|webp)$ {
        try_files $uri =404;
        expires max;
        access_log off;
    }
}
