server {
    listen 80;
    server_name localhost;

    # 1. Root & Index
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 301 /qc/;
    }

    location /qc/ {
        try_files $uri $uri/ /qc/index.html;
    }
#
#     error_page 404 /qc/index.html;
#     error_page 500 502 503 504 /50x.html;
#     location = /50x.html {
#         root /usr/share/nginx/html;
#     }

    location ~* \.(?:ico|css|js|map|woff|woff2|ttf|otf|eot|ttc|ttf|jpg|jpeg|gif|png|svg|webp)$ {
        try_files $uri =404;
        expires max;
        access_log off;
    }
}
